// Week 6 Casus 12 LME 1: Antibioticaresistentie en therapie
export { default as Image01IntroductieSummary } from './Image01IntroductieSummary'
export { default as Image02MenuSummary } from './Image02MenuSummary'
export { default as Image03IntrinsiekeVerworvenSummary } from './Image03IntrinsiekeVerworvenSummary'
export { default as Image04NatuurlijkeResistentieSummary } from './Image04NatuurlijkeResistentieSummary'
export { default as Image05CelwandSummary } from './Image05CelwandSummary'
export { default as Image06BetalactamSummary } from './Image06BetalactamSummary'
export { default as Image07WildtypeSummary } from './Image07WildtypeSummary'
export { default as Image08ResistentiemechanismenSummary } from './Image08ResistentiemechanismenSummary'
export { default as Image09BetalactamResistentieSummary } from './Image09BetalactamResistentieSummary'
export { default as Image10SAureusSummary } from './Image10SAureusSummary'
export { default as Image11MRSASummary } from './Image11MRSASummary'
export { default as Image12VoorkomenMRSASummary } from './Image12VoorkomenMRSASummary'
export { default as Image13BRMOSummary } from './Image13BRMOSummary'
export { default as Image14GevarenSummary } from './Image14GevarenSummary'
export { default as Image15SamenvattingSummary } from './Image15SamenvattingSummary'
