/**
 * Oefententamen Blok 4 – 60 inhoudelijke meerkeuzevragen
 * Gebaseerd op de stof uit alle samenvattingen.
 * Regels: uitdagende opties, gelijke lengte, alleen inhoudelijke vragen.
 */
export const examQuestions = [
  {
    id: 1,
    question: "Waarom zijn gramnegatieve bacteriën van nature resistent voor vancomycine?",
    options: [
      { letter: "A", text: "Vancomycine wordt door bètalactamase geïnactiveerd" },
      { letter: "B", text: "Vancomycine passeert de porines in de buitenmembraan niet" },
      { letter: "C", text: "Gramnegatieven hebben een te dikke peptidoglycaanlaag" },
      { letter: "D", text: "Vancomycine bindt niet aan het PBP-eiwit" },
    ],
    correctAnswer: "B",
    category: "Antibioticaresistentie",
  },
  {
    id: 2,
    question: "Welk resistentiemechanisme wordt door clavulaanzuur geremd?",
    options: [
      { letter: "A", text: "ESBL-productie" },
      { letter: "B", text: "Penicillinase-productie" },
      { letter: "C", text: "Carbapenemase-productie" },
      { letter: "D", text: "Effluxpomp-upregulatie" },
    ],
    correctAnswer: "B",
    category: "Antibioticaresistentie",
  },
  {
    id: 3,
    question: "Wat is een belangrijk verschil tussen ESBL en AmpC?",
    options: [
      { letter: "A", text: "ESBL is chromosomaal; AmpC is plasmide-gedragen" },
      { letter: "B", text: "ESBL-genen vaak op plasmiden; AmpC meestal chromosomaal" },
      { letter: "C", text: "AmpC inactiveren carbapenems; ESBL niet" },
      { letter: "D", text: "ESBL wordt geïnduceerd tijdens behandeling; AmpC niet" },
    ],
    correctAnswer: "B",
    category: "Antibioticaresistentie",
  },
  {
    id: 4,
    question: "Waarom is MRSA resistent voor alle beta-lactamantibiotica?",
    options: [
      { letter: "A", text: "Door productie van beta-lactamase" },
      { letter: "B", text: "Door modificatie van PBP2 naar PBP2a" },
      { letter: "C", text: "Door verminderde porine-opname" },
      { letter: "D", text: "Door upregulatie van effluxpompen" },
    ],
    correctAnswer: "B",
    category: "Antibioticaresistentie",
  },
  {
    id: 5,
    question: "Welke uitspraak over de SOFA-score bij sepsis is correct?",
    options: [
      { letter: "A", text: "Hartslag ≥90 en koorts ≥38°C zijn onderdeel van de SOFA" },
      { letter: "B", text: "SOFA bevat bewustzijn, trombocyten, kreatinine en MAP" },
      { letter: "C", text: "De SOFA wordt alleen bij opname berekend" },
      { letter: "D", text: "Lactaat ≥2 mmol/L is een SOFA-parameter" },
    ],
    correctAnswer: "B",
    category: "Sepsis",
  },
  {
    id: 6,
    question: "Wat is een belangrijk verschil tussen sepsis en septische shock?",
    options: [
      { letter: "A", text: "Septische shock vereist altijd positieve bloedkweken" },
      { letter: "B", text: "Septische shock: circulatoir falen met therapieresistente hypotensie" },
      { letter: "C", text: "Sepsis heeft alleen koorts; septische shock ook hypothermie" },
      { letter: "D", text: "Septische shock heeft altijd orgaanfalen; sepsis nooit" },
    ],
    correctAnswer: "B",
    category: "Sepsis",
  },
  {
    id: 7,
    question: "Welke vasopressor is eerste keuze bij septische shock?",
    options: [
      { letter: "A", text: "Adrenaline" },
      { letter: "B", text: "Noradrenaline" },
      { letter: "C", text: "Dopamine" },
      { letter: "D", text: "Vasopressine" },
    ],
    correctAnswer: "B",
    category: "Sepsis",
  },
  {
    id: 8,
    question: "Binnen welke termijn moeten empirische antibiotica bij sepsis idealiter worden gestart?",
    options: [
      { letter: "A", text: "Binnen 1 uur na presentatie" },
      { letter: "B", text: "Binnen 4 uur na presentatie" },
      { letter: "C", text: "Binnen 12 uur na presentatie" },
      { letter: "D", text: "Na bevestiging van positieve bloedkweken" },
    ],
    correctAnswer: "B",
    category: "Sepsis",
  },
  {
    id: 9,
    question: "Hoeveel kristalloïde vocht wordt bij hypotensie of lactaat ≥4 mmol/L aanbevolen in de eerste 3 uur?",
    options: [
      { letter: "A", text: "10 mL/kg" },
      { letter: "B", text: "20 mL/kg" },
      { letter: "C", text: "30 mL/kg" },
      { letter: "D", text: "50 mL/kg" },
    ],
    correctAnswer: "C",
    category: "Sepsis",
  },
  {
    id: 10,
    question: "Welke doel-MAP wordt bij septische shock nagestreefd?",
    options: [
      { letter: "A", text: "≥55 mmHg" },
      { letter: "B", text: "≥65 mmHg" },
      { letter: "C", text: "≥75 mmHg" },
      { letter: "D", text: "≥85 mmHg" },
    ],
    correctAnswer: "B",
    category: "Sepsis",
  },
  {
    id: 11,
    question: "Welk effect heeft methotrexaat als antimetaboliet?",
    options: [
      { letter: "A", text: "Remt T-celaanmaak door foliumzuuranalogie" },
      { letter: "B", text: "Blokkeert TNF-alfa direct" },
      { letter: "C", text: "Remt calcineurine" },
      { letter: "D", text: "Stimuleert B-celproliferatie" },
    ],
    correctAnswer: "A",
    category: "Immunomodulatie",
  },
  {
    id: 12,
    question: "Wat is een belangrijk verschil tussen actieve en passieve immunisatie?",
    options: [
      { letter: "A", text: "Actief geeft directe bescherming; passief langdurige" },
      { letter: "B", text: "Passief geeft directe maar tijdelijke bescherming" },
      { letter: "C", text: "Actieve immunisatie gebruikt immunoglobulinen" },
      { letter: "D", text: "Passieve immunisatie induceert immunologisch geheugen" },
    ],
    correctAnswer: "B",
    category: "Immunomodulatie",
  },
  {
    id: 13,
    question: "Welke bijwerking is kenmerkend voor calcineurine-remmers?",
    options: [
      { letter: "A", text: "Hepatotoxiciteit" },
      { letter: "B", text: "Nefrotoxiciteit" },
      { letter: "C", text: "Cardiotoxiciteit" },
      { letter: "D", text: "Pulmonale toxiciteit" },
    ],
    correctAnswer: "B",
    category: "Immunomodulatie",
  },
  {
    id: 14,
    question: "Wanneer moet dexamethason worden gegeven bij pneumokokkenmeningitis?",
    options: [
      { letter: "A", text: "Na sterilisatie van de liquor" },
      { letter: "B", text: "Vóór of gelijktijdig met eerste dosis antibiotica" },
      { letter: "C", text: "Alleen bij kinderen jonger dan 5 jaar" },
      { letter: "D", text: "Alleen bij resistente pneumokokken" },
    ],
    correctAnswer: "B",
    category: "Meningitis",
  },
  {
    id: 15,
    question: "Bij penicillinase-producerende S. aureus blijven welke antibiotica werkzaam?",
    options: [
      { letter: "A", text: "Penicilline en amoxicilline" },
      { letter: "B", text: "Flucloxacilline en cefalosporinen" },
      { letter: "C", text: "Alleen vancomycine" },
      { letter: "D", text: "Geen beta-lactams" },
    ],
    correctAnswer: "B",
    category: "Antibioticaresistentie",
  },
  {
    id: 16,
    question: "Wat betekent R₀ > 1 in een epidemiologisch model?",
    options: [
      { letter: "A", text: "De infectie verdwijnt uit de populatie" },
      { letter: "B", text: "Het aantal besmettingen blijft stabiel" },
      { letter: "C", text: "Er ontstaat een epidemie" },
      { letter: "D", text: "De populatie is volledig immuun" },
    ],
    correctAnswer: "C",
    category: "Vaccinatie",
  },
  {
    id: 17,
    question: "Welke factor is geen onderdeel van de formule R₀ = b × c × D?",
    options: [
      { letter: "A", text: "Besmettingskans per contact" },
      { letter: "B", text: "Aantal contacten" },
      { letter: "C", text: "Infectieduur" },
      { letter: "D", text: "Vaccinatiegraad" },
    ],
    correctAnswer: "D",
    category: "Vaccinatie",
  },
  {
    id: 18,
    question: "Welke verwekker van virale gastro-enteritis behoort tot de familie Caliciviridae?",
    options: [
      { letter: "A", text: "Rotavirus" },
      { letter: "B", text: "Norovirus" },
      { letter: "C", text: "Adenovirus" },
      { letter: "D", text: "Astrovirus" },
    ],
    correctAnswer: "B",
    category: "Virale gastro-enteritis",
  },
  {
    id: 19,
    question: "Voor welke virusfamilie is een virale toxine beschreven die dehydratie versterkt?",
    options: [
      { letter: "A", text: "Caliciviridae" },
      { letter: "B", text: "Reoviridae" },
      { letter: "C", text: "Adenoviridae" },
      { letter: "D", text: "Astroviridae" },
    ],
    correctAnswer: "B",
    category: "Virale gastro-enteritis",
  },
  {
    id: 20,
    question: "Wat is de eerste keuze behandeling bij milde tot matige dehydratie door virale gastro-enteritis?",
    options: [
      { letter: "A", text: "Intraveneuze vloeistoftherapie" },
      { letter: "B", text: "ORS (orale rehydratie)" },
      { letter: "C", text: "Antibiotica" },
      { letter: "D", text: "Anti-emetica als eerste keuze" },
    ],
    correctAnswer: "B",
    category: "Virale gastro-enteritis",
  },
  {
    id: 21,
    question: "Welke parasiet kan een amoebenabsces in de lever veroorzaken?",
    options: [
      { letter: "A", text: "Giardia lamblia" },
      { letter: "B", text: "Cryptosporidium" },
      { letter: "C", text: "Entamoeba histolytica" },
      { letter: "D", text: "Ascaris lumbricoides" },
    ],
    correctAnswer: "C",
    category: "Parasitaire gastro-enteritis",
  },
  {
    id: 22,
    question: "Wat is een belangrijk verschil tussen Safety I en Safety II?",
    options: [
      { letter: "A", text: "Safety I: preventie; Safety II: behandeling" },
      { letter: "B", text: "Safety I: foutgericht; Safety II: krachtgericht" },
      { letter: "C", text: "Safety I: prospectief; Safety II: retrospectief" },
      { letter: "D", text: "Safety I: medicatie; Safety II: chirurgie" },
    ],
    correctAnswer: "B",
    category: "Medicatieveiligheid",
  },
  {
    id: 23,
    question: "Welke infectie staat op de eerste plaats van de meest voorkomende zorggerelateerde infecties?",
    options: [
      { letter: "A", text: "Postoperatieve wondinfectie" },
      { letter: "B", text: "Urineweginfectie" },
      { letter: "C", text: "Lijninfectie" },
      { letter: "D", text: "Onderste luchtweginfectie" },
    ],
    correctAnswer: "B",
    category: "Zorggerelateerde infecties",
  },
  {
    id: 24,
    question: "Bij welke schimmelinfectie is het KOH-preparaat een geschikte diagnostische methode?",
    options: [
      { letter: "A", text: "Alleen bij candidiasis" },
      { letter: "B", text: "Dermatomycosen: KOH lost cellen op, hyfen blijven zichtbaar" },
      { letter: "C", text: "Alleen bij systemische infecties" },
      { letter: "D", text: "Niet bij tinea capitis" },
    ],
    correctAnswer: "B",
    category: "Schimmelinfecties",
  },
  {
    id: 25,
    question: "Waarom zijn gisten niet gevoelig voor terbinafine?",
    options: [
      { letter: "A", text: "Terbinafine werkt alleen tegen dermatofyten" },
      { letter: "B", text: "Gisten hebben een andere celwandstructuur" },
      { letter: "C", text: "Terbinafine wordt door gisten geïnactiveerd" },
      { letter: "D", text: "Gisten produceren resistentie-enzymen" },
    ],
    correctAnswer: "A",
    category: "Schimmelinfecties",
  },
  {
    id: 26,
    question: "Wanneer is orale antimycotische therapie geïndiceerd bij tinea capitis?",
    options: [
      { letter: "A", text: "Alleen bij uitgebreide laesies" },
      { letter: "B", text: "Om littekenvorming te voorkomen" },
      { letter: "C", text: "Alleen bij volwassenen" },
      { letter: "D", text: "Nooit; topische behandeling is altijd voldoende" },
    ],
    correctAnswer: "B",
    category: "Schimmelinfecties",
  },
  {
    id: 27,
    question: "Welke bacterie is een belangrijke bron van postoperatieve wondinfecties bij schone ingrepen?",
    options: [
      { letter: "A", text: "E. coli uit de darm" },
      { letter: "B", text: "S. aureus uit eigen huidflora" },
      { letter: "C", text: "Pseudomonas uit de omgeving" },
      { letter: "D", text: "Klebsiella uit de luchtwegen" },
    ],
    correctAnswer: "B",
    category: "Zorggerelateerde infecties",
  },
  {
    id: 28,
    question: "Hoeveel procent van de bevolking is asymptomatisch drager van S. aureus?",
    options: [
      { letter: "A", text: "Ongeveer 5%" },
      { letter: "B", text: "Ongeveer 15%" },
      { letter: "C", text: "Ongeveer 30%" },
      { letter: "D", text: "Ongeveer 50%" },
    ],
    correctAnswer: "C",
    category: "Zorggerelateerde infecties",
  },
  {
    id: 29,
    question: "Wat is een belangrijk verschil tussen PRI en PRISMA?",
    options: [
      { letter: "A", text: "PRI is retrospectief; PRISMA prospectief" },
      { letter: "B", text: "PRI is prospectief; PRISMA retrospectief" },
      { letter: "C", text: "PRI gaat over medicatie; PRISMA over chirurgie" },
      { letter: "D", text: "PRI is voor ziekenhuizen; PRISMA voor verpleeghuizen" },
    ],
    correctAnswer: "B",
    category: "Medicatieveiligheid",
  },
  {
    id: 30,
    question: "Welke uitspraak over carbapenemase-producerende bacteriën is correct?",
    options: [
      { letter: "A", text: "Carbapenemase wordt geremd door clavulaanzuur" },
      { letter: "B", text: "Carbapenemase inactiveren carbapenems" },
      { letter: "C", text: "Meropenem blijft werkzaam bij carbapenemase" },
      { letter: "D", text: "AmpC is een vorm van carbapenemase" },
    ],
    correctAnswer: "B",
    category: "Antibioticaresistentie",
  },
  {
    id: 31,
    question: "Binnen welke termijn moet bij bacteriële meningitis een breedspectrum antibioticum worden gestart?",
    options: [
      { letter: "A", text: "Binnen 30 minuten" },
      { letter: "B", text: "Binnen 1 uur" },
      { letter: "C", text: "Binnen 4 uur" },
      { letter: "D", text: "Na bevestiging van de verwekker" },
    ],
    correctAnswer: "B",
    category: "Meningitis",
  },
  {
    id: 32,
    question: "Hoe lang duurt de sterilisatie van de subarachnoïdale ruimte bij meningokokkenmeningitis?",
    options: [
      { letter: "A", text: "Ongeveer 30 minuten" },
      { letter: "B", text: "Ongeveer 2 uur" },
      { letter: "C", text: "4 tot 24 uur" },
      { letter: "D", text: "48 tot 72 uur" },
    ],
    correctAnswer: "B",
    category: "Meningitis",
  },
  {
    id: 33,
    question: "Welke vaccins induceren antilichamen tegen polysachariden van het bacteriële kapsel?",
    options: [
      { letter: "A", text: "Alleen levend verzwakte vaccins" },
      { letter: "B", text: "Vaccins tegen gekapselde bacteriën (pneumokokken)" },
      { letter: "C", text: "Alleen subunit-vaccins" },
      { letter: "D", text: "Alleen mRNA-vaccins" },
    ],
    correctAnswer: "B",
    category: "Vaccinatie",
  },
  {
    id: 34,
    question: "Welke verwekker van virale gastro-enteritis heeft serotype 40 en 41?",
    options: [
      { letter: "A", text: "Norovirus" },
      { letter: "B", text: "Rotavirus" },
      { letter: "C", text: "Adenovirus" },
      { letter: "D", text: "Astrovirus" },
    ],
    correctAnswer: "C",
    category: "Virale gastro-enteritis",
  },
  {
    id: 35,
    question: "Bij welke groep kan norovirusinfectie chronisch worden?",
    options: [
      { letter: "A", text: "Gezonde volwassenen" },
      { letter: "B", text: "Immuungecompromitteerden" },
      { letter: "C", text: "Zuigelingen" },
      { letter: "D", text: "Ouderen met intacte afweer" },
    ],
    correctAnswer: "B",
    category: "Virale gastro-enteritis",
  },
  {
    id: 36,
    question: "Bij welke parasiet is bloederige diarree een kenmerkend verschijnsel?",
    options: [
      { letter: "A", text: "Giardia lamblia" },
      { letter: "B", text: "Cryptosporidium" },
      { letter: "C", text: "Entamoeba histolytica" },
      { letter: "D", text: "Ascaris lumbricoides" },
    ],
    correctAnswer: "C",
    category: "Parasitaire gastro-enteritis",
  },
  {
    id: 37,
    question: "Welke uitspraak over intrinsieke resistentie is correct?",
    options: [
      { letter: "A", text: "Bacterie altijd resistent door ontoegankelijke doelmoleculen" },
      { letter: "B", text: "Intrinsieke resistentie ontstaat door mutatie" },
      { letter: "C", text: "Intrinsieke resistentie wordt via plasmiden overgedragen" },
      { letter: "D", text: "Intrinsieke resistentie is hetzelfde als verworven resistentie" },
    ],
    correctAnswer: "A",
    category: "Antibioticaresistentie",
  },
  {
    id: 38,
    question: "Wat is een belangrijk verschil tussen ESBL en AmpC?",
    options: [
      { letter: "A", text: "ESBL kan worden geïnduceerd; AmpC niet" },
      { letter: "B", text: "Bij AmpC zijn penicillines/cefalosporines gevaarlijk bij ernstige infecties" },
      { letter: "C", text: "ESBL inactiveren carbapenems; AmpC niet" },
      { letter: "D", text: "AmpC is altijd plasmide-gedragen" },
    ],
    correctAnswer: "B",
    category: "Antibioticaresistentie",
  },
  {
    id: 39,
    question: "Welke maatregel hoort bij BRMO-beleid?",
    options: [
      { letter: "A", text: "Alleen handhygiëne" },
      { letter: "B", text: "Isolatie en aangepaste reiniging" },
      { letter: "C", text: "Geen antibiotica meer" },
      { letter: "D", text: "Verplichte screening van alle patiënten" },
    ],
    correctAnswer: "B",
    category: "Antibioticaresistentie",
  },
  {
    id: 40,
    question: "Welke uitspraak over het SIR-model is correct?",
    options: [
      { letter: "A", text: "S staat voor symptomatisch; I voor immuun" },
      { letter: "B", text: "S = vatbaar; I = geïnfecteerd; R = hersteld/immuun" },
      { letter: "C", text: "Het model heeft geen R₀" },
      { letter: "D", text: "Re is altijd gelijk aan R₀" },
    ],
    correctAnswer: "B",
    category: "Vaccinatie",
  },
  {
    id: 41,
    question: "Welke factor beïnvloedt de besmettingskans (b) in de formule R₀ = b × c × D?",
    options: [
      { letter: "A", text: "Vaccinatie en handhygiëne" },
      { letter: "B", text: "Alleen het aantal contacten" },
      { letter: "C", text: "Alleen de infectieduur" },
      { letter: "D", text: "Geen van deze" },
    ],
    correctAnswer: "A",
    category: "Vaccinatie",
  },
  {
    id: 42,
    question: "Wanneer begint het rotavirusvaccinatieschema volgens het RVP?",
    options: [
      { letter: "A", text: "Direct na de geboorte" },
      { letter: "B", text: "Tussen 6 en 9 weken" },
      { letter: "C", text: "Rond 3 maanden" },
      { letter: "D", text: "Rond 6 maanden" },
    ],
    correctAnswer: "B",
    category: "Virale gastro-enteritis",
  },
  {
    id: 43,
    question: "Wat is een contra-indicatie voor het rotavirusvaccin?",
    options: [
      { letter: "A", text: "Lichte koorts" },
      { letter: "B", text: "Invaginatie in de anamnese" },
      { letter: "C", text: "Prematuriteit" },
      { letter: "D", text: "Lactatie" },
    ],
    correctAnswer: "B",
    category: "Virale gastro-enteritis",
  },
  {
    id: 44,
    question: "Welke klinische presentatie past bij tinea corporis?",
    options: [
      { letter: "A", text: "Vesiculae op erythemateuze ondergrond" },
      { letter: "B", text: "Annulaire plek met verheven rand, opheldering midden" },
      { letter: "C", text: "Geelverkleuring van de nagels" },
      { letter: "D", text: "Alopecia zonder schilfering" },
    ],
    correctAnswer: "B",
    category: "Schimmelinfecties",
  },
  {
    id: 45,
    question: "Waarom is orale antimycotische therapie vaak nodig bij onychomycose?",
    options: [
      { letter: "A", text: "Topische middelen werken niet tegen dermatofyten" },
      { letter: "B", text: "Topische middelen dringen niet goed door in de nagel" },
      { letter: "C", text: "Orale middelen hebben minder bijwerkingen" },
      { letter: "D", text: "Onychomycose is altijd systemisch" },
    ],
    correctAnswer: "B",
    category: "Schimmelinfecties",
  },
  {
    id: 46,
    question: "Welke uitspraak over TNF-alfa is correct?",
    options: [
      { letter: "A", text: "TNF-alfa heeft alleen effect op cytokinen" },
      { letter: "B", text: "TNF-alfa heeft pleiotrope effecten (cytokinen, adhesie, angiogenese)" },
      { letter: "C", text: "Anti-TNF-alfa wordt alleen bij reuma gebruikt" },
      { letter: "D", text: "TNF-alfa remt ontsteking" },
    ],
    correctAnswer: "B",
    category: "Immunomodulatie",
  },
  {
    id: 47,
    question: "Welke bacterie is een belangrijke grampositieve verwekker van sepsis?",
    options: [
      { letter: "A", text: "E. coli" },
      { letter: "B", text: "Klebsiella pneumoniae" },
      { letter: "C", text: "Staphylococcus aureus" },
      { letter: "D", text: "Pseudomonas aeruginosa" },
    ],
    correctAnswer: "C",
    category: "Sepsis",
  },
  {
    id: 48,
    question: "Wat is een belangrijk verschil tussen bacteriemie en sepsis?",
    options: [
      { letter: "A", text: "Bacteriemie heeft altijd orgaanfalen" },
      { letter: "B", text: "Sepsis = orgaanfalen door ontregelde gastheerrespons" },
      { letter: "C", text: "Bacteriemie is altijd ernstiger dan sepsis" },
      { letter: "D", text: "Sepsis vereist altijd positieve bloedkweken" },
    ],
    correctAnswer: "B",
    category: "Sepsis",
  },
  {
    id: 49,
    question: "Welke maatregel vermindert medicatiefouten bij organisatiefalen?",
    options: [
      { letter: "A", text: "Meer personeel per patiënt" },
      { letter: "B", text: "Gelijkende geneesmiddelen niet naast elkaar leggen" },
      { letter: "C", text: "Minder controle op verdeling" },
      { letter: "D", text: "Snellere verdeling" },
    ],
    correctAnswer: "B",
    category: "Medicatieveiligheid",
  },
  {
    id: 50,
    question: "Wat is een belangrijk verschil tussen hospital-acquired en community-acquired infecties?",
    options: [
      { letter: "A", text: "Hospital-acquired zijn altijd milder" },
      { letter: "B", text: "Verwekkers verschillen; empirisch beleid moet worden aangepast" },
      { letter: "C", text: "Community-acquired zijn altijd resistenter" },
      { letter: "D", text: "Er is geen verschil in behandeling" },
    ],
    correctAnswer: "B",
    category: "Zorggerelateerde infecties",
  },
  {
    id: 51,
    question: "Sinds wanneer worden antibiotica op grote schaal gebruikt bij mens en dier?",
    options: [
      { letter: "A", text: "Sinds de jaren 20" },
      { letter: "B", text: "Sinds de jaren 40" },
      { letter: "C", text: "Sinds de jaren 60" },
      { letter: "D", text: "Sinds de jaren 80" },
    ],
    correctAnswer: "B",
    category: "Antibioticaresistentie",
  },
  {
    id: 52,
    question: "Welke resistentie is een voorbeeld van verworven resistentie?",
    options: [
      { letter: "A", text: "Gramnegatieven voor vancomycine" },
      { letter: "B", text: "Mutatie en selectie onder antibiotische druk" },
      { letter: "C", text: "Aerobe bacteriën voor metronidazol" },
      { letter: "D", text: "Anaerobe bacteriën voor aminoglycosiden" },
    ],
    correctAnswer: "B",
    category: "Antibioticaresistentie",
  },
  {
    id: 53,
    question: "Wat is een potentieel nadeel van dexamethason bij pneumokokkenmeningitis?",
    options: [
      { letter: "A", text: "Verhoogde liquorproductie" },
      { letter: "B", text: "Remming van het aangeboren immuunsysteem" },
      { letter: "C", text: "Versnelling van antibioticumresistentie" },
      { letter: "D", text: "Verlenging van de sterilisatietijd" },
    ],
    correctAnswer: "B",
    category: "Meningitis",
  },
  {
    id: 54,
    question: "Hoe lang duurt de sterilisatie van de subarachnoïdale ruimte bij pneumokokkenmeningitis?",
    options: [
      { letter: "A", text: "Ongeveer 30 minuten" },
      { letter: "B", text: "Ongeveer 2 uur" },
      { letter: "C", text: "4 tot 24 uur" },
      { letter: "D", text: "48 tot 72 uur" },
    ],
    correctAnswer: "C",
    category: "Meningitis",
  },
  {
    id: 55,
    question: "Welke uitspraak over Re (effectief reproductiegetal) is correct?",
    options: [
      { letter: "A", text: "Re is altijd gelijk aan R₀" },
      { letter: "B", text: "Re daalt door immuniteit en maatregelen" },
      { letter: "C", text: "Re is alleen relevant bij R₀ < 1" },
      { letter: "D", text: "Re is het aantal primaire gevallen" },
    ],
    correctAnswer: "B",
    category: "Vaccinatie",
  },
  {
    id: 56,
    question: "Welke verwekker van virale gastro-enteritis heeft dubbelstrengs gesegmenteerd RNA?",
    options: [
      { letter: "A", text: "Norovirus" },
      { letter: "B", text: "Rotavirus" },
      { letter: "C", text: "Adenovirus" },
      { letter: "D", text: "Astrovirus" },
    ],
    correctAnswer: "B",
    category: "Virale gastro-enteritis",
  },
  {
    id: 57,
    question: "Bij welke parasiet is winderigheid en brijige diarree kenmerkend?",
    options: [
      { letter: "A", text: "Giardia lamblia" },
      { letter: "B", text: "Cryptosporidium" },
      { letter: "C", text: "Entamoeba histolytica" },
      { letter: "D", text: "Ascaris lumbricoides" },
    ],
    correctAnswer: "A",
    category: "Parasitaire gastro-enteritis",
  },
  {
    id: 58,
    question: "Welke antimycotica zijn effectief tegen dermatofyten?",
    options: [
      { letter: "A", text: "Alleen azolen" },
      { letter: "B", text: "Terbinafine en azolen" },
      { letter: "C", text: "Alleen nystatine" },
      { letter: "D", text: "Alleen amphotericine B" },
    ],
    correctAnswer: "B",
    category: "Schimmelinfecties",
  },
  {
    id: 59,
    question: "Welke uitspraak over de mortaliteit bij sepsis is correct?",
    options: [
      { letter: "A", text: "Mortaliteit is altijd onder 5%" },
      { letter: "B", text: "Mortaliteit is 15–50% afhankelijk van ernst" },
      { letter: "C", text: "Mortaliteit is hoger bij grampositieve verwekkers" },
      { letter: "D", text: "Mortaliteit is niet afhankelijk van behandeling" },
    ],
    correctAnswer: "B",
    category: "Sepsis",
  },
  {
    id: 60,
    question: "Wat is het doel van vaccins tegen gekapselde bacteriën?",
    options: [
      { letter: "A", text: "Doding van de bacterie direct" },
      { letter: "B", text: "Antilichamen tegen kapselpolysachariden (opsonisatie)" },
      { letter: "C", text: "Remming van toxineproductie" },
      { letter: "D", text: "Preventie van adhesie" },
    ],
    correctAnswer: "B",
    category: "Vaccinatie",
  },
]
