// Week 5 Casus 7 LME 1: Huidmanifestaties infectieziekten – bacteriën Pneumococcen en meningococcen
export const pneumococcenMeningococcenQuestions = [
  {
    id: 1,
    question: "Welke twee bacteriën behoren tot de meest dodelijke in de reguliere Nederlandse geneeskundige zorg?",
    options: [
      { letter: "A", text: "Escherichia coli en Staphylococcus aureus" },
      { letter: "B", text: "Streptococcus pneumoniae en Neisseria meningitidis" },
      { letter: "C", text: "Haemophilus influenzae en Klebsiella pneumoniae" },
      { letter: "D", text: "Mycobacterium tuberculosis en Bordetella pertussis" },
    ],
    correctAnswer: "B",
    category: "Introductie",
  },
  {
    id: 2,
    question: "Door welk systeem wordt de surveillance van invasieve pneumokokkenziekte in Nederland uitgevoerd?",
    options: [
      { letter: "A", text: "Landelijk meldingssysteem door alle huisartsen" },
      { letter: "B", text: "Sentinel-laboratoriumsurveillancesysteem door NRLBM (AMC/RIVM)" },
      { letter: "C", text: "Ziekenhuisregistraties" },
      { letter: "D", text: "WHO Global Surveillance Network" },
    ],
    correctAnswer: "B",
    category: "Epidemiologie",
  },
  {
    id: 3,
    question: "Welke leeftijdsgroep heeft de hoogste incidentie van invasieve pneumokokkenziekte?",
    options: [
      { letter: "A", text: "Kinderen <5 jaar" },
      { letter: "B", text: "5-49 jaar" },
      { letter: "C", text: "50-64 jaar" },
      { letter: "D", text: "65 jaar en ouder" },
    ],
    correctAnswer: "D",
    category: "Epidemiologie",
  },
  {
    id: 4,
    question: "Welke verklaring past bij de hoge incidentie van pneumokokkenziekte bij ouderen?",
    options: [
      { letter: "A", text: "Te veel blootstelling aan zonlicht" },
      { letter: "B", text: "Verminderde weerstand door veroudering, verminderde barrièrefunctie, verminderde functie van alveolaire macrofagen" },
      { letter: "C", text: "Overmatige vaccinatie" },
      { letter: "D", text: "Geen van bovenstaande" },
    ],
    correctAnswer: "B",
    category: "Epidemiologie",
  },
  {
    id: 5,
    question: "Bij welke leeftijdsgroepen zijn de meldingspercentages van meningokokkenziekte het hoogst?",
    options: [
      { letter: "A", text: "Alleen volwassenen 30-50 jaar" },
      { letter: "B", text: "Zuigelingen, gevolgd door jonge kinderen en adolescenten" },
      { letter: "C", text: "Alleen 65-plussers" },
      { letter: "D", text: "Alleen peuters 2-4 jaar" },
    ],
    correctAnswer: "B",
    category: "Epidemiologie",
  },
  {
    id: 6,
    question: "Waarom is de incidentie van pneumokokkeninfecties hoger dan die van meningokokkeninfecties?",
    options: [
      { letter: "A", text: "Meningokokken zijn dodelijker" },
      { letter: "B", text: "Pneumokokken zijn geassocieerd met veel diverse infecties (o.a. pneumonie, otitis media); een groot aantal wordt niet gemeld" },
      { letter: "C", text: "Er is geen vaccin tegen pneumokokken" },
      { letter: "D", text: "Meningokokken komen alleen in tropische landen voor" },
    ],
    correctAnswer: "B",
    category: "Epidemiologie",
  },
  {
    id: 7,
    question: "Welke bacterie is de belangrijkste verwekker van bacteriële meningitis in Nederland (grootste aandeel)?",
    options: [
      { letter: "A", text: "Neisseria meningitidis" },
      { letter: "B", text: "Streptococcus pneumoniae" },
      { letter: "C", text: "Haemophilus influenzae" },
      { letter: "D", text: "Escherichia coli" },
    ],
    correctAnswer: "B",
    category: "Kliniek",
  },
  {
    id: 8,
    question: "Welke gekapselde bacteriën zijn voorbeelden waartegen vaccinaties worden gegeven?",
    options: [
      { letter: "A", text: "Pneumokokken, Influenza A+B, Meningokokken" },
      { letter: "B", text: "Pneumokokken, Haemophilus influenzae type b, Meningokokken" },
      { letter: "C", text: "Groep A streptococcen, Staphylococcus aureus, Escherichia coli" },
      { letter: "D", text: "Mycobacterium tuberculosis, Bordetella pertussis" },
    ],
    correctAnswer: "B",
    category: "Vaccins",
  },
  {
    id: 9,
    question: "Wat is het primaire doel van vaccins tegen gekapselde bacteriën?",
    options: [
      { letter: "A", text: "Het stimuleren van de productie van interferon-gamma" },
      { letter: "B", text: "Het induceren van specifieke antilichamen gericht tegen polysachariden van het bacteriële kapsel" },
      { letter: "C", text: "Het verhogen van de productie van polysachariden door het immuunsysteem" },
      { letter: "D", text: "Het verhogen van de weerstand tegen virale infecties" },
    ],
    correctAnswer: "B",
    category: "Vaccins",
  },
  {
    id: 10,
    question: "Welk type vaccin wordt gebruikt voor meningokokken en pneumokokken?",
    options: [
      { letter: "A", text: "mRNA vaccin dat kapseleiwitten tot expressie brengt" },
      { letter: "B", text: "Polysachariden gekoppeld aan een eiwit (geconjugeerd vaccin)" },
      { letter: "C", text: "Levend verzwakt vaccin" },
      { letter: "D", text: "Toxine vaccin" },
    ],
    correctAnswer: "B",
    category: "Vaccins",
  },
  {
    id: 11,
    question: "Hoe werken de antilichamen die worden geproduceerd door vaccins tegen gekapselde bacteriën?",
    options: [
      { letter: "A", text: "Ze remmen de celdeling van de bacteriën direct" },
      { letter: "B", text: "Ze markeren de bacteriën voor vernietiging door het immuunsysteem (opsonisatie)" },
      { letter: "C", text: "Ze blokkeren de productie van het bacteriële kapsel" },
      { letter: "D", text: "Ze stimuleren de aanmaak van cytokines die de bacteriën vernietigen" },
    ],
    correctAnswer: "B",
    category: "Vaccins",
  },
  {
    id: 12,
    question: "Waarom worden geconjugeerde vaccins gebruikt voor sommige gekapselde bacteriën?",
    options: [
      { letter: "A", text: "Omdat ze de polysachariden afbreken voordat de bacterie kan infecteren" },
      { letter: "B", text: "Omdat ze gekoppeld zijn aan een eiwitdrager, wat een sterkere immuunrespons genereert, vooral bij jonge kinderen" },
      { letter: "C", text: "Omdat ze alleen effectief zijn tegen virale infecties" },
      { letter: "D", text: "Omdat ze de bacterie direct doden zonder hulp van het immuunsysteem" },
    ],
    correctAnswer: "B",
    category: "Vaccins",
  },
  {
    id: 13,
    question: "Welke aandoening verhoogt het infectierisico door gekapselde bacteriën zoals pneumokokken?",
    options: [
      { letter: "A", text: "Hypertensie" },
      { letter: "B", text: "Asplenie (afwezige of niet-functionerende milt)" },
      { letter: "C", text: "Diabetes type 2" },
      { letter: "D", text: "Astma" },
    ],
    correctAnswer: "B",
    category: "Kliniek",
  },
  {
    id: 14,
    question: "Welk symptoom onderscheidt meningokokkenmeningitis van pneumokokkenmeningitis?",
    options: [
      { letter: "A", text: "Koorts" },
      { letter: "B", text: "Petechiën" },
      { letter: "C", text: "Hoofdpijn" },
      { letter: "D", text: "Stijve nek" },
    ],
    correctAnswer: "B",
    category: "Kliniek",
  },
  {
    id: 15,
    question: "Wat zijn petechiën?",
    options: [
      { letter: "A", text: "Grote blaren op de huid" },
      { letter: "B", text: "Kleine, niet-wegdrukbare puntbloedingen (0,5-1 mm)" },
      { letter: "C", text: "Rode vlekken die vervagen bij druk" },
      { letter: "D", text: "Puistjes veroorzaakt door bacteriën" },
    ],
    correctAnswer: "B",
    category: "Petechiën",
  },
  {
    id: 16,
    question: "Wat moet je doen bij een patiënt met hoge koorts en petechiën?",
    options: [
      { letter: "A", text: "Afwachten en paracetamol voorschrijven" },
      { letter: "B", text: "Denken aan meningokokkensepsis of -meningitis; direct verwijzen naar het ziekenhuis" },
      { letter: "C", text: "Alleen bloedonderzoek aanvragen" },
      { letter: "D", text: "Antibiotica oraal voorschrijven" },
    ],
    correctAnswer: "B",
    category: "Petechiën",
  },
  {
    id: 17,
    question: "Welke bacterie is een belangrijke infectieuze oorzaak van petechiën?",
    options: [
      { letter: "A", text: "Escherichia coli" },
      { letter: "B", text: "Neisseria meningitidis" },
      { letter: "C", text: "Clostridium difficile" },
      { letter: "D", text: "Helicobacter pylori" },
    ],
    correctAnswer: "B",
    category: "Petechiën",
  },
  {
    id: 18,
    question: "Binnen welke tijd moet bij verdenking op bacteriële meningitis een breedspectrum IV-antibioticum worden gestart?",
    options: [
      { letter: "A", text: "Binnen 24 uur" },
      { letter: "B", text: "Binnen 12 uur" },
      { letter: "C", text: "Binnen 4 uur" },
      { letter: "D", text: "Binnen het eerste uur" },
    ],
    correctAnswer: "D",
    category: "Behandeling",
  },
  {
    id: 19,
    question: "Wat is een potentieel nadeel van dexamethason bij pneumokokkeninfectie?",
    options: [
      { letter: "A", text: "Verhoogde bloeddruk" },
      { letter: "B", text: "Remming van het aangeboren immuunsysteem (macrofagen, neutrofielen)" },
      { letter: "C", text: "Hyperglykemie" },
      { letter: "D", text: "Gewichtstoename" },
    ],
    correctAnswer: "B",
    category: "Behandeling",
  },
  {
    id: 20,
    question: "Welke meningokokkenserogroepen zitten in het Rijksvaccinatieprogramma (MenACWY)?",
    options: [
      { letter: "A", text: "Alleen B" },
      { letter: "B", text: "A, C, W en Y" },
      { letter: "C", text: "Alleen C" },
      { letter: "D", text: "A, B, C, W en Y" },
    ],
    correctAnswer: "B",
    category: "Vaccins",
  },
]
