// LME 3: Welk antibioticum kies ik (Week 5 Casus 9) - Image-based summaries
export { default as Image01IntroductieSummary } from './Image01IntroductieSummary'
export { default as Image02MenuSummary } from './Image02MenuSummary'
export { default as Image03IntroductieStofnamenSummary } from './Image03IntroductieStofnamenSummary'
export { default as Image04PrincipesFocusSummary } from './Image04PrincipesFocusSummary'
export { default as Image05EmpirieSummary } from './Image05EmpirieSummary'
export { default as Image06ToedieningswegSummary } from './Image06ToedieningswegSummary'
export { default as Image07GevoeligheidSummary } from './Image07GevoeligheidSummary'
export { default as Image08EUCASTSummary } from './Image08EUCASTSummary'
export { default as Image09FarmacokinetiekSummary } from './Image09FarmacokinetiekSummary'
export { default as Image10FarmacodynamiekSummary } from './Image10FarmacodynamiekSummary'
export { default as Image11ContraIndicatiesSummary } from './Image11ContraIndicatiesSummary'
export { default as Image12KostenSummary } from './Image12KostenSummary'
export { default as Image13RichtlijnenSummary } from './Image13RichtlijnenSummary'
export { default as Image14CombinatiesSummary } from './Image14CombinatiesSummary'
