// Auto-generated by scripts/generate-blok9-mini-summaries.mjs — do not edit by hand.
// Regenerate:  node scripts/generate-blok9-mini-summaries.mjs

import config0 from './week-1/casus-1/acute-nierschade-mini.jsx'
import config1 from './week-1/casus-1/acute-nierschade-verdieping-mini.jsx'
import config2 from './week-1/casus-1/glomerulaire-en-tubulaire-nierziekten-mini.jsx'
import config3 from './week-1/casus-1/glomerulaire-nierziekten-mini.jsx'
import config4 from './week-1/casus-1/tubulaire-en-erfelijke-nierziekten-mini.jsx'
import config5 from './week-1/casus-2/chronische-nierschade-mini.jsx'
import config6 from './week-1/casus-2/chronische-nierschade-verdieping-mini.jsx'
import config7 from './week-1/casus-2/dialyse-mini.jsx'
import config8 from './week-1/casus-2/ethiek-van-orgaantransplantatie-mini.jsx'
import config9 from './week-1/casus-2/nierfunctievervangende-therapie-mini.jsx'
import config10 from './week-1/casus-2/niertransplantatie-mini.jsx'
import config11 from './week-2/casus-3/klinische-stoornissen-kaliumbalans-mini.jsx'
import config12 from './week-2/casus-3/klinische-stoornissen-water-en-volume-balans-mini.jsx'
import config13 from './week-2/casus-3/klinische-stoornissen-zuur-basebalans-mini.jsx'
import config14 from './week-2/casus-3/stoornissen-kalium-en-zuur-base-evenwicht-verdieping-mini.jsx'
import config15 from './week-2/casus-3/stoornissen-water-en-volumebalans-verdieping-mini.jsx'
import config16 from './week-2/casus-4/ct-scans-beoordelen-vow-toegepaste-anatomie-mini.jsx'
import config17 from './week-2/casus-4/diabetische-voet-mini.jsx'
import config18 from './week-2/casus-4/dilaterend-vaatlijden-mini.jsx'
import config19 from './week-2/casus-4/mdr-juridische-aspecten-medische-tools-mini.jsx'
import config20 from './week-2/casus-4/perifeer-arterieel-vaatlijden-mini.jsx'
import config21 from './week-2/casus-4/preoperatieve-screening-mini.jsx'
import config22 from './week-3/casus-5/ai-act-mini.jsx'
import config23 from './week-3/casus-5/farmacogenetica-mini.jsx'
import config24 from './week-3/casus-5/hypertensie-mini.jsx'
import config25 from './week-3/casus-5/hypertensief-spoedgeval-mini.jsx'
import config26 from './week-3/casus-5/secundaire-hypertensie-mini.jsx'
import config27 from './week-3/casus-6/cvrm-mini.jsx'
import config28 from './week-4/casus-7/klinisch-redeneren-respiratoire-insufficientie-mini.jsx'
import config29 from './week-4/casus-7/pathofysiologie-kliniek-diagnostiek-pneumonie-mini.jsx'
import config30 from './week-4/casus-7/pneumonie-epidemiologie-verwekkers-behandeling-mini.jsx'
import config31 from './week-4/casus-7/symptomatische-behandeling-respiratoire-insufficientie-mini.jsx'
import config32 from './week-4/casus-8/herkennen-gedecompenseerde-circulatie-en-alarmsymptomen-mini.jsx'
import config33 from './week-4/casus-8/lineare-regressielijn-mini.jsx'
import config34 from './week-4/casus-8/passende-zorg-op-de-intensive-care-mini.jsx'
import config35 from './week-4/casus-8/shock-mini.jsx'
import config36 from './week-4/casus-8/toxidromen-mini.jsx'
import config37 from './week-5/casus-10/atriumfibrilleren-mini.jsx'
import config38 from './week-5/casus-10/basis-analyse-ecg-mini.jsx'
import config39 from './week-5/casus-10/brady-aritmie-en-implanteerbare-cardiale-devices-mini.jsx'
import config40 from './week-5/casus-10/elektrofysiologisch-onderzoek-en-ablaties-mini.jsx'
import config41 from './week-5/casus-10/leefstijl-als-therapie-voor-atriumfibrilleren-mini.jsx'
import config42 from './week-5/casus-10/ritmestoornissen-bij-kinderen-mini.jsx'
import config43 from './week-5/casus-10/syncope-mini.jsx'
import config44 from './week-5/casus-10/tachyaritmie-mini.jsx'
import config45 from './week-5/casus-9/longkanker-mini.jsx'
import config46 from './week-5/casus-9/pleuravocht-mini.jsx'
import config47 from './week-5/casus-9/voorbereiding-ct-en-pet-ct-mini.jsx'
import config48 from './week-5/casus-9/voorbereiding-pathologie-longkanker-mini.jsx'

const BLOK9_MINI_CONFIG = {
  "blok9-week1-casus1-acute-nierschade-mini": config0,
  "blok9-week1-casus1-acute-nierschade-verdieping-mini": config1,
  "blok9-week1-casus1-glomerulaire-en-tubulaire-nierziekten-mini": config2,
  "blok9-week1-casus1-glomerulaire-nierziekten-mini": config3,
  "blok9-week1-casus1-tubulaire-en-erfelijke-nierziekten-mini": config4,
  "blok9-week1-casus2-chronische-nierschade-mini": config5,
  "blok9-week1-casus2-chronische-nierschade-verdieping-mini": config6,
  "blok9-week1-casus2-dialyse-mini": config7,
  "blok9-week1-casus2-ethiek-van-orgaantransplantatie-mini": config8,
  "blok9-week1-casus2-nierfunctievervangende-therapie-mini": config9,
  "blok9-week1-casus2-niertransplantatie-mini": config10,
  "blok9-week2-casus3-klinische-stoornissen-kaliumbalans-mini": config11,
  "blok9-week2-casus3-klinische-stoornissen-water-en-volume-balans-mini": config12,
  "blok9-week2-casus3-klinische-stoornissen-zuur-basebalans-mini": config13,
  "blok9-week2-casus3-stoornissen-kalium-en-zuur-base-evenwicht-verdieping-mini": config14,
  "blok9-week2-casus3-stoornissen-water-en-volumebalans-verdieping-mini": config15,
  "blok9-week2-casus4-ct-scans-beoordelen-vow-toegepaste-anatomie-mini": config16,
  "blok9-week2-casus4-diabetische-voet-mini": config17,
  "blok9-week2-casus4-dilaterend-vaatlijden-mini": config18,
  "blok9-week2-casus4-mdr-juridische-aspecten-medische-tools-mini": config19,
  "blok9-week2-casus4-perifeer-arterieel-vaatlijden-mini": config20,
  "blok9-week2-casus4-preoperatieve-screening-mini": config21,
  "blok9-week3-casus5-ai-act-mini": config22,
  "blok9-week3-casus5-farmacogenetica-mini": config23,
  "blok9-week3-casus5-hypertensie-mini": config24,
  "blok9-week3-casus5-hypertensief-spoedgeval-mini": config25,
  "blok9-week3-casus5-secundaire-hypertensie-mini": config26,
  "blok9-week3-casus6-cvrm-mini": config27,
  "blok9-week4-casus7-klinisch-redeneren-respiratoire-insufficiëntie-mini": config28,
  "blok9-week4-casus7-pathofysiologie-kliniek-diagnostiek-pneumonie-mini": config29,
  "blok9-week4-casus7-pneumonie-epidemiologie-verwekkers-behandeling-mini": config30,
  "blok9-week4-casus7-symptomatische-behandeling-respiratoire-insufficientie-mini": config31,
  "blok9-week4-casus8-herkennen-gedecompenseerde-circulatie-en-alarmsymptomen-mini": config32,
  "blok9-week4-casus8-lineare-regressielijn-mini": config33,
  "blok9-week4-casus8-passende-zorg-op-de-intensive-care-mini": config34,
  "blok9-week4-casus8-shock-mini": config35,
  "blok9-week4-casus8-toxidromen-mini": config36,
  "blok9-week5-casus10-atriumfibrilleren-mini": config37,
  "blok9-week5-casus10-basis-analyse-ecg-mini": config38,
  "blok9-week5-casus10-brady-aritmie-en-implanteerbare-cardiale-devices-mini": config39,
  "blok9-week5-casus10-elektrofysiologisch-onderzoek-en-ablaties-mini": config40,
  "blok9-week5-casus10-leefstijl-als-therapie-voor-atriumfibrilleren-mini": config41,
  "blok9-week5-casus10-ritmestoornissen-bij-kinderen-mini": config42,
  "blok9-week5-casus10-syncope-mini": config43,
  "blok9-week5-casus10-tachyaritmie-mini": config44,
  "blok9-week5-casus9-longkanker-mini": config45,
  "blok9-week5-casus9-pleuravocht-mini": config46,
  "blok9-week5-casus9-voorbereiding-ct-en-pet-ct-mini": config47,
  "blok9-week5-casus9-voorbereiding-pathologie-longkanker-mini": config48,
}

export function getBlok9MiniConfig(miniLmeId) {
  return BLOK9_MINI_CONFIG[miniLmeId] || null
}

export function isBlok9MiniLme(lmeId) {
  return Boolean(lmeId && BLOK9_MINI_CONFIG[lmeId])
}

export const BLOK9_MINI_IDS = Object.keys(BLOK9_MINI_CONFIG)
