import { blok10Week3CasusC06DmType1LmoEndocrieneRegulatieKhVetEnEiwitstofwisselingQuestionsPart01 } from './Blok10Week3CasusC06DmType1LmoEndocrieneRegulatieKhVetEnEiwitstofwisselingQuestionsPart01'
import { blok10Week3CasusC06DmType1LmoEndocrieneRegulatieKhVetEnEiwitstofwisselingQuestionsPart02 } from './Blok10Week3CasusC06DmType1LmoEndocrieneRegulatieKhVetEnEiwitstofwisselingQuestionsPart02'

export const blok10Week3CasusC06DmType1LmoEndocrieneRegulatieKhVetEnEiwitstofwisselingQuestionsMap = {
  'blok10-week3-casus-c06-dm-type1-lmo-endocriene-regulatie-kh-vet-en-eiwitstofwisseling-part01':
    blok10Week3CasusC06DmType1LmoEndocrieneRegulatieKhVetEnEiwitstofwisselingQuestionsPart01,
  'blok10-week3-casus-c06-dm-type1-lmo-endocriene-regulatie-kh-vet-en-eiwitstofwisseling-part02':
    blok10Week3CasusC06DmType1LmoEndocrieneRegulatieKhVetEnEiwitstofwisselingQuestionsPart02,
}
