// LME 6: Voorbereiding VOW Milt (Week 5 Casus 7) - Image-based summaries
export { default as Image01IntroductieSummary } from './Image01IntroductieSummary'
export { default as Image02MenuSummary } from './Image02MenuSummary'
export { default as Image03FunctiesDiagramSummary } from './Image03FunctiesDiagramSummary'
export { default as Image04FunctiesVideoSummary } from './Image04FunctiesVideoSummary'
export { default as Image05StructurenMiltSummary } from './Image05StructurenMiltSummary'
export { default as Image06RodeWittePulpaSummary } from './Image06RodeWittePulpaSummary'
export { default as Image07RodePulpaStructurenSummary } from './Image07RodePulpaStructurenSummary'
export { default as Image08WittePulpaStructurenSummary } from './Image08WittePulpaStructurenSummary'
export { default as Image09PALSSummary } from './Image09PALSSummary'
export { default as Image10OpenGeslotenCirculatieSummary } from './Image10OpenGeslotenCirculatieSummary'
export { default as Image11OpenCirculatieBelangrijkSummary } from './Image11OpenCirculatieBelangrijkSummary'
export { default as Image12OpenCirculatieRouteSummary } from './Image12OpenCirculatieRouteSummary'
export { default as Image13GeslotenCirculatieSummary } from './Image13GeslotenCirculatieSummary'
export { default as Image14AfsluitingSummary } from './Image14AfsluitingSummary'
