// Auto-generated by scripts/generate-blok5-mini-summaries.mjs — do not edit by hand.
// Regenerate:  node scripts/generate-blok5-mini-summaries.mjs

import config0 from './week-1/casus-1/de-huidbarriere-van-jong-tot-oud-mini.jsx'
import config1 from './week-1/casus-1/externe-verstorende-factoren-op-de-huidbarriere-mini.jsx'
import config2 from './week-1/casus-1/hoe-werkt-een-geneesmiddel-via-de-huid-mini.jsx'
import config3 from './week-1/casus-1/huidtypen-met-invloed-van-uva-en-uvb-mini.jsx'
import config4 from './week-1/casus-1/microbioom-en-immunologie-van-de-huid-mini.jsx'
import config5 from './week-1/casus-2/lmo-eczeem-mini.jsx'
import config6 from './week-1/casus-2/lmv-anafylaxie-type-i-allergie-mini.jsx'
import config7 from './week-1/casus-2/lmv-centrale-vs-perifere-tolerantie-mini.jsx'
import config8 from './week-1/casus-2/lmv-contact-allergie-en-allergologisch-onderzoek-mini.jsx'
import config9 from './week-1/casus-2/nadelige-reacties-van-medicatie-mini.jsx'
import config10 from './week-1/casus-2/provoke-mini.jsx'
import config11 from './week-1/casus-2/psoriasis-mini.jsx'
import config12 from './week-1/casus-2/stm-pathogenese-type-iv-allergie-mini.jsx'
import config13 from './week-1/casus-2/voeding-en-inhalatieallergie-mini.jsx'
import config14 from './week-2/casus-3/aangeboren-stollingsstoornissen-mini.jsx'
import config15 from './week-2/casus-3/begripsbepaling-dermatologische-uitingen-mini.jsx'
import config16 from './week-2/casus-3/hemostase-basis-mini.jsx'
import config17 from './week-2/casus-3/lmv-vasculitis-of-vasculopathie-mini.jsx'
import config18 from './week-2/casus-3/vasculitis-klein-middel-groot-mini.jsx'
import config19 from './week-2/casus-4/chronische-ontsteking-mini.jsx'
import config20 from './week-2/casus-4/goedaardige-en-kwaadaardige-huidafwijkingen-mini.jsx'
import config21 from './week-2/casus-4/immuuntherapie-van-kanker-mini.jsx'
import config22 from './week-2/casus-4/melanoom-gelokaliseerd-mini.jsx'
import config23 from './week-2/casus-4/mri-en-pet-scan-benignemaligne-mini.jsx'
import config24 from './week-2/casus-4/sentinel-node-mini.jsx'
import config25 from './week-2/casus-4/systemische-therapie-van-melanoom-mini.jsx'
import config26 from './week-3/casus-5/huidtumoren-basaalcel-en-plaveiselcelcarcinoom-mini.jsx'
import config27 from './week-3/casus-5/huidtumoren-benigne-en-premaligne-mini.jsx'
import config28 from './week-3/casus-5/leefstijl-en-kanker-mini.jsx'
import config29 from './week-3/casus-5/lmo-verdachte-huidafwijkingen-mini.jsx'
import config30 from './week-3/casus-5/lmo-zorgmijding-mini.jsx'
import config31 from './week-3/casus-5/milieu-en-gezondheid-mini.jsx'
import config32 from './week-3/casus-6/behandeling-van-mammacarcinoom-mini.jsx'
import config33 from './week-3/casus-6/familiair-mammacarcinoom-mini.jsx'
import config34 from './week-3/casus-6/het-slechtnieuwsgesprek-mini.jsx'
import config35 from './week-3/casus-6/mammapathologie-mini.jsx'
import config36 from './week-3/casus-6/overdiagnose-bij-bevolkingsonderzoek-mammacarcinoom-mini.jsx'
import config37 from './week-3/casus-6/radiologische-diagnostiek-mammacarcinoom-mini.jsx'
import config38 from './week-4/casus-7/flebologische-aandoeningen-mini.jsx'
import config39 from './week-4/casus-7/lmo-differentiaal-diagnostische-aanpak-zwelling-been-mini.jsx'
import config40 from './week-4/casus-7/lmo-voorbereiding-vow-hoeveel-mag-een-levensjaar-kosten-mini.jsx'
import config41 from './week-4/casus-7/lymfadenopathie-mini.jsx'
import config42 from './week-4/casus-7/trombose-verhoogde-stollingsneiging-mini.jsx'
import config43 from './week-4/casus-8/erysipelas-en-cellulitis-mini.jsx'
import config44 from './week-4/casus-8/hydradenitis-suppurativa-mini.jsx'
import config45 from './week-4/casus-8/introductiemodule-planetary-health-mini.jsx'
import config46 from './week-4/casus-8/lichamelijk-onderzoek-knie-voorbereiding-klv-1-24-mini.jsx'
import config47 from './week-4/casus-8/lmv-verworven-stollingsstoornissen-mini.jsx'
import config48 from './week-4/casus-8/lymfeklierdissectie-mini.jsx'
import config49 from './week-4/casus-8/necrotiserende-wekedeleninfectie-mini.jsx'
import config50 from './week-4/casus-8/radiotherapie-in-de-praktijk-mini.jsx'
import config51 from './week-4/casus-8/volksgezondheidsindicatoren-dalys-mini.jsx'
import config52 from './week-5/casus-10/lmo-traps-fmf-en-hids-mini.jsx'
import config53 from './week-5/casus-10/lmv-sarcoidose-presentatie-en-pathogenese-mini.jsx'
import config54 from './week-5/casus-10/principes-en-klinische-aspecten-van-auto-inflammatie-mini.jsx'
import config55 from './week-5/casus-10/spectrum-auto-inflammatie-en-auto-immuniteit-mini.jsx'
import config56 from './week-5/casus-11/alarmsymptomen-op-de-kinderleeftijd-mini.jsx'
import config57 from './week-5/casus-11/introductie-kinderoncologie-mini.jsx'
import config58 from './week-5/casus-11/kinderoncologie-begrijp-de-hallmarks-mini.jsx'
import config59 from './week-5/casus-11/lmo-importziekten-mini.jsx'
import config60 from './week-5/casus-11/lmo-infecties-binnen-de-kinderoncologie-mini.jsx'
import config61 from './week-5/casus-11/over-leven-na-kanker-op-kinderleeftijd-mini.jsx'
import config62 from './week-5/casus-11/typen-kinderoncologie-bij-kinderen-mini.jsx'
import config63 from './week-5/casus-9/bouw-en-functie-van-de-thymus-mini.jsx'
import config64 from './week-5/casus-9/endocriene-auto-immuunziekten-mini.jsx'
import config65 from './week-5/casus-9/lmo-positieve-en-negatieve-selectie-mini.jsx'
import config66 from './week-5/casus-9/lmo-voorbereiding-vo-ra-klinische-presentatie-en-immuunmechanismen-mini.jsx'
import config67 from './week-5/casus-9/lmv-auto-immuniteit-als-bijwerking-bij-immunotherapie-mini.jsx'
import config68 from './week-5/casus-9/lmv-introductie-auto-immuniteit-versus-auto-inflammatie-mini.jsx'
import config69 from './week-5/casus-9/lmv-patient-met-sle-samenvatting-mini.jsx'
import config70 from './week-5/casus-9/pathogenese-auto-immuunziekten-mini.jsx'
import config71 from './week-6/casus-12/gaswisseling-hb-o2-co2-co-mini.jsx'
import config72 from './week-6/casus-12/nvic-acute-vergiftiging-mini.jsx'
import config73 from './week-6/casus-12/slechte-woningen-lucht-luchtverontreiniging-bovenste-luchtweginfecties-mini.jsx'
import config74 from './week-6/casus-13/botopbouw-botafbraak-en-pathologische-breuken-mini.jsx'
import config75 from './week-6/casus-13/celtherapie-als-behandeling-voor-maligniteiten-mini.jsx'
import config76 from './week-6/casus-13/het-mm-als-voorbeeld-voor-targeted-therapy-in-de-hemato-oncologie-mini.jsx'
import config77 from './week-6/casus-13/m-proteine-diagnostiek-eiwit-als-tumormarker-mini.jsx'
import config78 from './week-6/casus-13/transplantatiegeneeskunde-mini.jsx'
import config79 from './week-7/casus-14/dermatoloog-in-je-broekzak-mini.jsx'
import config80 from './week-7/casus-14/lmo-ethiek-van-derma-apps-mini.jsx'
import config81 from './week-7/casus-14/lmo-implementatie-in-de-dermatologische-praktijk-mini.jsx'
import config82 from './week-7/casus-14/lmo-wat-is-ai-mini.jsx'
import config83 from './week-8/casus-15/lmo-voorbereiding-vow-palliatieve-zorg-mini.jsx'
import config84 from './week-8/casus-15/remmen-versus-stimuleren-van-het-afweersysteem-mini.jsx'
import config85 from './week-8/casus-15/risico-op-iatrogene-schade-na-orgaantransplantatie-mini.jsx'
import config86 from './week-8/casus-15/scylla-en-charybdis-mini.jsx'

const BLOK5_MINI_CONFIG = {
  "blok5-week1-casus1-de-huidbarriere-van-jong-tot-oud-mini": config0,
  "blok5-week1-casus1-externe-verstorende-factoren-op-de-huidbarriere-mini": config1,
  "blok5-week1-casus1-hoe-werkt-een-geneesmiddel-via-de-huid-mini": config2,
  "blok5-week1-casus1-huidtypen-met-invloed-van-uva-en-uvb-mini": config3,
  "blok5-week1-casus1-microbioom-en-immunologie-van-de-huid-mini": config4,
  "blok5-week1-casus2-lmo-eczeem-mini": config5,
  "blok5-week1-casus2-lmv-anafylaxie-type-i-allergie-mini": config6,
  "blok5-week1-casus2-lmv-centrale-vs-perifere-tolerantie-mini": config7,
  "blok5-week1-casus2-lmv-contact-allergie-en-allergologisch-onderzoek-mini": config8,
  "blok5-week1-casus2-nadelige-reacties-van-medicatie-mini": config9,
  "blok5-week1-casus2-provoke-mini": config10,
  "blok5-week1-casus2-psoriasis-mini": config11,
  "blok5-week1-casus2-stm-pathogenese-type-iv-allergie-mini": config12,
  "blok5-week1-casus2-voeding-en-inhalatieallergie-mini": config13,
  "blok5-week2-casus3-aangeboren-stollingsstoornissen-mini": config14,
  "blok5-week2-casus3-begripsbepaling-dermatologische-uitingen-mini": config15,
  "blok5-week2-casus3-hemostase-basis-mini": config16,
  "blok5-week2-casus3-lmv-vasculitis-of-vasculopathie-mini": config17,
  "blok5-week2-casus3-vasculitis-klein-middel-groot-mini": config18,
  "blok5-week2-casus4-chronische-ontsteking-mini": config19,
  "blok5-week2-casus4-goedaardige-en-kwaadaardige-huidafwijkingen-mini": config20,
  "blok5-week2-casus4-immuuntherapie-van-kanker-mini": config21,
  "blok5-week2-casus4-melanoom-gelokaliseerd-mini": config22,
  "blok5-week2-casus4-mri-en-pet-scan-benignemaligne-mini": config23,
  "blok5-week2-casus4-sentinel-node-mini": config24,
  "blok5-week2-casus4-systemische-therapie-van-melanoom-mini": config25,
  "blok5-week3-casus5-huidtumoren-basaalcel-en-plaveiselcelcarcinoom-mini": config26,
  "blok5-week3-casus5-huidtumoren-benigne-en-premaligne-mini": config27,
  "blok5-week3-casus5-leefstijl-en-kanker-mini": config28,
  "blok5-week3-casus5-lmo-verdachte-huidafwijkingen-mini": config29,
  "blok5-week3-casus5-lmo-zorgmijding-mini": config30,
  "blok5-week3-casus5-milieu-en-gezondheid-mini": config31,
  "blok5-week3-casus6-behandeling-van-mammacarcinoom-mini": config32,
  "blok5-week3-casus6-familiair-mammacarcinoom-mini": config33,
  "blok5-week3-casus6-het-slechtnieuwsgesprek-mini": config34,
  "blok5-week3-casus6-mammapathologie-mini": config35,
  "blok5-week3-casus6-overdiagnose-bij-bevolkingsonderzoek-mammacarcinoom-mini": config36,
  "blok5-week3-casus6-radiologische-diagnostiek-mammacarcinoom-mini": config37,
  "blok5-week4-casus7-flebologische-aandoeningen-mini": config38,
  "blok5-week4-casus7-lmo-differentiaal-diagnostische-aanpak-zwelling-been-mini": config39,
  "blok5-week4-casus7-lmo-voorbereiding-vow-hoeveel-mag-een-levensjaar-kosten-mini": config40,
  "blok5-week4-casus7-lymfadenopathie-mini": config41,
  "blok5-week4-casus7-trombose-verhoogde-stollingsneiging-mini": config42,
  "blok5-week4-casus8-erysipelas-en-cellulitis-mini": config43,
  "blok5-week4-casus8-hydradenitis-suppurativa-mini": config44,
  "blok5-week4-casus8-introductiemodule-planetary-health-mini": config45,
  "blok5-week4-casus8-lichamelijk-onderzoek-knie-voorbereiding-klv-1-24-mini": config46,
  "blok5-week4-casus8-lmv-verworven-stollingsstoornissen-mini": config47,
  "blok5-week4-casus8-lymfeklierdissectie-mini": config48,
  "blok5-week4-casus8-necrotiserende-wekedeleninfectie-mini": config49,
  "blok5-week4-casus8-radiotherapie-in-de-praktijk-mini": config50,
  "blok5-week4-casus8-volksgezondheidsindicatoren-dalys-mini": config51,
  "blok5-week5-casus10-lmo-traps-fmf-en-hids-mini": config52,
  "blok5-week5-casus10-lmv-sarcoidose-presentatie-en-pathogenese-mini": config53,
  "blok5-week5-casus10-principes-en-klinische-aspecten-van-auto-inflammatie-mini": config54,
  "blok5-week5-casus10-spectrum-auto-inflammatie-en-auto-immuniteit-mini": config55,
  "blok5-week5-casus11-alarmsymptomen-op-de-kinderleeftijd-mini": config56,
  "blok5-week5-casus11-introductie-kinderoncologie-mini": config57,
  "blok5-week5-casus11-kinderoncologie-begrijp-de-hallmarks-mini": config58,
  "blok5-week5-casus11-lmo-importziekten-mini": config59,
  "blok5-week5-casus11-lmo-infecties-binnen-de-kinderoncologie-mini": config60,
  "blok5-week5-casus11-over-leven-na-kanker-op-kinderleeftijd-mini": config61,
  "blok5-week5-casus11-typen-kinderoncologie-bij-kinderen-mini": config62,
  "blok5-week5-casus9-bouw-en-functie-van-de-thymus-mini": config63,
  "blok5-week5-casus9-endocriene-auto-immuunziekten-mini": config64,
  "blok5-week5-casus9-lmo-positieve-en-negatieve-selectie-mini": config65,
  "blok5-week5-casus9-lmo-voorbereiding-vo-ra-klinische-presentatie-en-immuunmechanismen-mini": config66,
  "blok5-week5-casus9-lmv-auto-immuniteit-als-bijwerking-bij-immunotherapie-mini": config67,
  "blok5-week5-casus9-lmv-introductie-auto-immuniteit-versus-auto-inflammatie-mini": config68,
  "blok5-week5-casus9-lmv-patient-met-sle-samenvatting-mini": config69,
  "blok5-week5-casus9-pathogenese-auto-immuunziekten-mini": config70,
  "blok5-week6-casus12-gaswisseling-hb-o2-co2-co-mini": config71,
  "blok5-week6-casus12-nvic-acute-vergiftiging-mini": config72,
  "blok5-week6-casus12-slechte-woningen-lucht-luchtverontreiniging-bovenste-luchtweginfecties-mini": config73,
  "blok5-week6-casus13-botopbouw-botafbraak-en-pathologische-breuken-mini": config74,
  "blok5-week6-casus13-celtherapie-als-behandeling-voor-maligniteiten-mini": config75,
  "blok5-week6-casus13-het-mm-als-voorbeeld-voor-targeted-therapy-in-de-hemato-oncologie-mini": config76,
  "blok5-week6-casus13-m-proteine-diagnostiek-eiwit-als-tumormarker-mini": config77,
  "blok5-week6-casus13-transplantatiegeneeskunde-mini": config78,
  "blok5-week7-casus14-dermatoloog-in-je-broekzak-mini": config79,
  "blok5-week7-casus14-lmo-ethiek-van-derma-apps-mini": config80,
  "blok5-week7-casus14-lmo-implementatie-in-de-dermatologische-praktijk-mini": config81,
  "blok5-week7-casus14-lmo-wat-is-ai-mini": config82,
  "blok5-week8-casus15-lmo-voorbereiding-vow-palliatieve-zorg-mini": config83,
  "blok5-week8-casus15-remmen-versus-stimuleren-van-het-afweersysteem-mini": config84,
  "blok5-week8-casus15-risico-op-iatrogene-schade-na-orgaantransplantatie-mini": config85,
  "blok5-week8-casus15-scylla-en-charybdis-mini": config86,
}

export function getBlok5MiniConfig(miniLmeId) {
  return BLOK5_MINI_CONFIG[miniLmeId] || null
}

export function isBlok5MiniLme(lmeId) {
  return Boolean(lmeId && BLOK5_MINI_CONFIG[lmeId])
}

export const BLOK5_MINI_IDS = Object.keys(BLOK5_MINI_CONFIG)
